# Generated by Django 2.1a1 on 2018-06-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ablbum_title',
            new_name='album_title',
        ),
    ]
